# Numpy

## License

This IPython Notebook is released under the [Creative Commons Attribution-NonCommercial 3.0 Unported License](http://creativecommons.org/licenses/by-nc/3.0/)

## Introduction

**NumPy** is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object.
* sophisticated (broadcasting) functions.
* tools for integrating C/C++ and Fortran code.
* useful linear algebra, Fourier transform, and random number capabilities.


## Numpy Array

Suppose we have a function $f(x)$ and want to evaluate this function at a number of $x$ points $x_0, x_1,\dots , x_{n−1}$.

We could collect the `n` pairs $(x_i , f(x_i))$ in a list, or we could collect all the $x_i$ values, for $i = 0 \dots ,n−1$, in a list and all the associated $f(x_i)$ values in another list.

In [1]:
def f(x):
    return x**3

n=5
dx = 1.0/(n-1)
xlist = [ i*dx for i in range(n)]
ylist = [ f(x) for x in xlist]
pairs = [[x, y] for x, y in zip(xlist, ylist)]

print(xlist)
print(ylist)
print(pairs)

[0.0, 0.25, 0.5, 0.75, 1.0]
[0.0, 0.015625, 0.125, 0.421875, 1.0]
[[0.0, 0.0], [0.25, 0.015625], [0.5, 0.125], [0.75, 0.421875], [1.0, 1.0]]


But it is not easy to work with this.

A `numpy` **array** object can be viewed as a variant of a list, but with the following assumptions and features:

* All elements must be of the same type, preferably integer, real, or complex numbers.
* The number of elements must be known when the array is created.
* Arrays are not part of standard Python, one needs an additional package called Numerical Python, often abbreviated as **NumPy**.
* With `numpy`, a wide range of mathematical operations can be done directly on complete arrays, thereby removing the need for loops over array elements.
* Arrays with one index are often called vectors. Arrays with two indices are used as an efficient data structure for tables, instead of lists of lists. Arrays can also have three or more indices.

The standard import statement for Numerical Python reads

In [2]:
import numpy as np

To convert a list or a tuple to an array, we use the `array` function from numpy:

In [3]:
r = [1,2,3,4]
v = np.array(r)
print(v)
print(type(v))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
r = (1,2,3,4)
v = np.array(r)
print(v)
print(type(v))

[1 2 3 4]
<class 'numpy.ndarray'>


To create a new array of length n, filled with zeros, we write

In [6]:
n = 50000
v = np.zeros(n)
print(v)

[ 0.  0.  0. ...,  0.  0.  0.]


Use the second argument to create a new array of length n, filled with zeros of other types

In [7]:
n = 50000
v = np.zeros(n, int)
print(v)

[0 0 0 ..., 0 0 0]


To generates an array of zeros where the length is that of the array `r` and the element type is the same as those in `r`.

In [9]:
r1 = [1,2,3,4,5,6,7,7,7,7]
v1 = np.zeros_like(r1)
print(v1)

r2 = [1.,2.,3.,4.]
v2 = np.zeros_like(r2)
print(v2)

[0 0 0 0 0 0 0 0 0 0]
[ 0.  0.  0.  0.]


To generate an array to have `n` elements with *uniformly disributed* values in an interval $[p, q]$ one uses `linspace`.

In [12]:
p = 0.0
q = 10.0
n = 101
a = np.linspace(p, q, n)
print(a)

[  0.    0.1   0.2   0.3   0.4   0.5   0.6   0.7   0.8   0.9   1.    1.1
   1.2   1.3   1.4   1.5   1.6   1.7   1.8   1.9   2.    2.1   2.2   2.3
   2.4   2.5   2.6   2.7   2.8   2.9   3.    3.1   3.2   3.3   3.4   3.5
   3.6   3.7   3.8   3.9   4.    4.1   4.2   4.3   4.4   4.5   4.6   4.7
   4.8   4.9   5.    5.1   5.2   5.3   5.4   5.5   5.6   5.7   5.8   5.9
   6.    6.1   6.2   6.3   6.4   6.5   6.6   6.7   6.8   6.9   7.    7.1
   7.2   7.3   7.4   7.5   7.6   7.7   7.8   7.9   8.    8.1   8.2   8.3
   8.4   8.5   8.6   8.7   8.8   8.9   9.    9.1   9.2   9.3   9.4   9.5
   9.6   9.7   9.8   9.9  10. ]


### Index, slice, copying

Array elements are accessed by square brackets as for lists:

In [13]:
a = np.linspace(1., 10., 10)
print(a)
print(a[2])

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
3.0


In [14]:
a[2]=-1

In [15]:
a

array([  1.,   2.,  -1.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

Slices also work as for lists, for example, `a[1:-1]` picks out all elements except the first and the last.


In [16]:
a = np.linspace(1., 10., 10)
print(a[1:-1])

[ 2.  3.  4.  5.  6.  7.  8.  9.]


But contrary to lists, `a[1:-1]` is **not** a copy of the data in `a`. Hence,

In [17]:
a = np.linspace(1., 10., 10)
b = a[1:-1]
print('b=', b)
b[2] = 0.1
print('a=', a)
print('a[3]=', a[3])

b= [ 2.  3.  4.  5.  6.  7.  8.  9.]
a= [  1.    2.    3.    0.1   5.    6.    7.    8.    9.   10. ]
a[3]= 0.1


will also change `a[3]` to 0.1.`

Let `a` be an array. The statement `b = a` makes a refer to the same array as `a`. Changing `b` will then also affect `a`.

In [12]:
a = np.linspace(1., 10., 10)
print('a=', a)
b = a
b[-1] = 3000
print('a=', a)

a= [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
a= [  1.00000000e+00   2.00000000e+00   3.00000000e+00   4.00000000e+00
   5.00000000e+00   6.00000000e+00   7.00000000e+00   8.00000000e+00
   9.00000000e+00   3.00000000e+03]


Changing `b` without changing `a` requires `b` to be a copy of `a`:

In [13]:
a = np.linspace(1., 10., 10)
print('a=', a)
b = a.copy()
b[-1] = 3000
print('b=', b)
print('a=', a)

a= [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
b= [  1.00000000e+00   2.00000000e+00   3.00000000e+00   4.00000000e+00
   5.00000000e+00   6.00000000e+00   7.00000000e+00   8.00000000e+00
   9.00000000e+00   3.00000000e+03]
a= [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


### Vectorization

Loops over very long arrays may run slowly. A great advantage with arrays is that we can get rid of the loops and apply f directly to the whole array:


In [18]:
def f(x):
    return x**3

x = [1.0, 2.0, 3.0, 4.0]
f(x)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [20]:
fx= [f(xi) for xi in x]

In [21]:
def f(x):
    return x**3

n = 5
x = np.linspace(0, 1, n)
y = f(x)

print(x)
print(y)

[ 0.    0.25  0.5   0.75  1.  ]
[ 0.        0.015625  0.125     0.421875  1.      ]


In [22]:
n = 5
x = np.linspace(0, 1, n)
y = x**3

print(x)
print(y)

[ 0.    0.25  0.5   0.75  1.  ]
[ 0.        0.015625  0.125     0.421875  1.      ]


`numpy` implements vector arithmetics for arrays of any dimension.

`numpy` provides its own versions of math ematical functions like `cos`, `sin`, `exp`, `log`, etc., which work for array arguments and apply the mathematical function to each element.

In [23]:
import math

n = 5
x = np.linspace(0, 1, n)
r = np.zeros(len(x))
for i in range(len(x)):
    r[i] = math.sin(x[i])*math.cos(x[i])*math.exp(-x[i]**2) + 2 + x[i]**2
print(r)

[ 2.          2.28768931  2.57766913  2.84667776  3.16725591]


In [24]:
n = 5
x = np.linspace(0, 1, n)
# r = np.zeros(len(x))
r = np.sin(x) * np.cos(x) * np.exp(-x**2) + 2 + x**2
print(r)

[ 2.          2.28768931  2.57766913  2.84667776  3.16725591]


Scalar code:

In [20]:
n = 10
x = np.zeros(n)
y = np.zeros(n)
dx = 2.0/(n-1) # spacing of x coordinates
for i in range(n):
    x[i] = -1 + dx*i
    y[i] = math.exp(-x[i])*x[i]
print(x)
print(y)

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
[-2.71828183 -1.69293439 -0.96828278 -0.46520414 -0.12416879  0.09942659
  0.23884377  0.3187519   0.3573312   0.36787944]


Vectorized code:

In [25]:
n = 10
x = np.linspace(-1, 1, n)
y = np.exp(-x)*x

print(x)
print(y)

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
[-2.71828183 -1.69293439 -0.96828278 -0.46520414 -0.12416879  0.09942659
  0.23884377  0.3187519   0.3573312   0.36787944]


List comprehensions result in scalar code:

In [22]:
n = 10
dx = 2.0/(n-1) # spacing of x coordinates
x = np.array([-1 + dx*i for i in range(n)])
y = np.array([np.exp(-xi)*xi for xi in x])
print(x)
print(y)

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
[-2.71828183 -1.69293439 -0.96828278 -0.46520414 -0.12416879  0.09942659
  0.23884377  0.3187519   0.3573312   0.36787944]


### `arange`

`arange` creates an “arrange range” that is similar to the `range` except it returns a numpy array and the step doesn’t have to be an integer.

In [23]:
print(np.arange(0, 1, 0.25))
print(np.arange(0, 1.01, 0.25))

[ 0.    0.25  0.5   0.75]
[ 0.    0.25  0.5   0.75  1.  ]


### `linspace`

`linspace` creates an “linearly-spaced” array that is similar to `arange` except instead of the step value you tell it the number of points you want. The resulting array will contain both endpoints and evenly-spaced values between those points.


In [24]:
print(np.linspace(0, 1, 5))

[ 0.    0.25  0.5   0.75  1.  ]


### `logspace`

`logspace` is like `linspace` but the values are spaced so that they are evenly distributed on a logarithmic scale. The stop and start values should be given as the powers of 10 that are desired.

In [25]:
print(np.logspace(0, 3, 4))
print(np.logspace(1, 3, 4))

[    1.    10.   100.  1000.]
[   10.            46.41588834   215.443469    1000.        ]


### `zeros`

`zeros(shape, dtype=float, order='C')` 

Return a new array of given shape and type, filled with zeros.

In [26]:
print(np.zeros(5))

[ 0.  0.  0.  0.  0.]


In [27]:
print(np.zeros(5, dtype=np.int))

[0 0 0 0 0]


### `ones`

`ones(shape, dtype=None, order='C')` 

Return a new array of given shape and type, filled with ones.

In [28]:
print(np.ones(5))

[ 1.  1.  1.  1.  1.]


In [29]:
print(np.ones(5, dtype=np.int))

[1 1 1 1 1]


### `zeros_like`

`zeros_like(a, dtype=None, order='K', subok=True)` 

Return an array of zeros with the same shape and type as a given array.


In [30]:
x = np.arange(6)
y = np.zeros_like(x)
print(x)
print(y)

[0 1 2 3 4 5]
[0 0 0 0 0 0]


### `ones_like`

`ones_like(a, dtype=None, order='K', subok=True)`

Return an array of ones with the same shape and type as a given array.

In [31]:
x = np.arange(6)
y = np.ones_like(x)
print(x)
print(y)

[0 1 2 3 4 5]
[1 1 1 1 1 1]


## 2D array

A list of lists is not a 2D array:

In [26]:
M= [ [1,2], [3,4] ]

In [27]:
print(M*3)

[[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]]


In [28]:
print(M+M)

[[1, 2], [3, 4], [1, 2], [3, 4]]


In [29]:
print(M*M)

TypeError: can't multiply sequence by non-int of type 'list'

To create NumPy 2D array

In [30]:
table = np.array([[-30, -22.0], [-20, -4.0], [-10, 14.0]])
print(table)

[[-30. -22.]
 [-20.  -4.]
 [-10.  14.]]


NumPy 2D array is NOT a matrix.

In [31]:
table_sqr = table * table
print(table_sqr)

[[ 900.  484.]
 [ 400.   16.]
 [ 100.  196.]]


## `shape` and `reshape'

In [33]:
import numpy as np
x = np.arange(6)
print(x)
print(x.shape)
print(table.shape)

[0 1 2 3 4 5]
(6,)
(3, 2)


In [34]:
x = np.linspace(1, 30, 30)
print(x.shape)
print(x)

(30,)
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]


In [35]:
t = x.reshape(5, 6)
print(t.shape)
print(t)

(5, 6)
[[  1.   2.   3.   4.   5.   6.]
 [  7.   8.   9.  10.  11.  12.]
 [ 13.  14.  15.  16.  17.  18.]
 [ 19.  20.  21.  22.  23.  24.]
 [ 25.  26.  27.  28.  29.  30.]]


## slice on 2D array

In [36]:
print(t[1:-1:2, 2:])

[[  9.  10.  11.  12.]
 [ 21.  22.  23.  24.]]


Use `numpy` to create 2D array:

In [37]:
import numpy as np

M = np.array([ [1,2], [3,4] ])
print('M=', M)
print('M*3=', M*3)
print('M+M=', M+M)
print('M*M=', M*M)

M= [[1 2]
 [3 4]]
M*3= [[ 3  6]
 [ 9 12]]
M+M= [[2 4]
 [6 8]]
M*M= [[ 1  4]
 [ 9 16]]


In [38]:
print("transpose")
print(np.transpose(M))

transpose
[[1 3]
 [2 4]]


## 3D array

In [39]:
x = np.linspace(1, 30, 30)
x = x.reshape(2,3,5)
print(x)

[[[  1.   2.   3.   4.   5.]
  [  6.   7.   8.   9.  10.]
  [ 11.  12.  13.  14.  15.]]

 [[ 16.  17.  18.  19.  20.]
  [ 21.  22.  23.  24.  25.]
  [ 26.  27.  28.  29.  30.]]]


In [40]:
print(x[0])

[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.]]


## numpy matrix

`numpy` also has a matrix type called `matrix` or `mat` for one- and two-dimensional arrays.


In [41]:
x1 = np.array([1, 2, 3], float)
x2 = np.matrix(x1)
print(type(x1))
print(type(x2))
x2

<class 'numpy.ndarray'>
<class 'numpy.matrixlib.defmatrix.matrix'>


matrix([[ 1.,  2.,  3.]])

In [42]:
x3 = x2.transpose()
x3

matrix([[ 1.],
        [ 2.],
        [ 3.]])

In [48]:
isinstance(x3, np.matrix)

True

In [43]:
print(x2)
print(x3)

[[ 1.  2.  3.]]
[[ 1.]
 [ 2.]
 [ 3.]]


In [44]:
A = np.eye(3)
A

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [45]:
A = np.mat(A)
A

matrix([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])

In [46]:
x2

matrix([[ 1.,  2.,  3.]])

In [47]:
# matrix-vector product
y2 = x2*A
y2

matrix([[ 1.,  2.,  3.]])

In [48]:
# matrix-vector product
y3 = A*x3 
y3

matrix([[ 1.],
        [ 2.],
        [ 3.]])

In [49]:
# no matrix-array product!
A*x1

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

### `dot` method

Dot product of two arrays.

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D
arrays to inner product of vectors (without complex conjugation).

In [50]:
M = np.array([ [0,1], [1,0] ])
print(M)
print(M*M)
print(np.dot(M,M))

[[0 1]
 [1 0]]
[[0 1]
 [1 0]]
[[1 0]
 [0 1]]


In [51]:
vec = np.array([1, 2, 3])
print(np.dot(vec, vec))

14


In [52]:
vec = np.array([1, 2j, 3])
print(np.dot(vec, vec))

(6+0j)


## Sub-module Linear algebra (`numpy.linalg`)

[`numpy.linalg`](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

In [53]:
M = np.array([ [1,2], [3,4] ])

In [54]:
# inverse
M_inv = np.linalg.inv(M)
print(M_inv)
print(np.dot(M, M_inv))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[  1.00000000e+00   1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]


In [55]:
# determinant 
print(np.linalg.det(M))

-2.0


In [56]:
M = np.array([ [0,1], [1,0] ])

# eigensystems
print(np.linalg.eigh(M))

(array([-1.,  1.]), array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]]))


In [57]:
vals, vecs = np.linalg.eig(M)

In [58]:
vals

array([ 1., -1.])

In [59]:
vecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [66]:
print(np.dot(M, vecs))

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


### use matrix language

In [60]:
M = np.matrix([ [1,2], [3,4] ])

# inverse
M_inv = np.linalg.inv(M)
print(M_inv)
print(M*M_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[  1.00000000e+00   1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]


In [61]:
M = np.matrix([ [0,1], [1,0] ])

# eigensystems
vals, vecs = np.linalg.eig(M)

In [62]:
vals

array([ 1., -1.])

In [63]:
vecs

matrix([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]])

In [64]:
vecs[:,0]

matrix([[ 0.70710678],
        [ 0.70710678]])

In [65]:
v0 = vecs[:, 0]
v0

matrix([[ 0.70710678],
        [ 0.70710678]])

In [73]:
M*v0-vals[0]*v0

matrix([[ 0.],
        [ 0.]])

In [74]:
M*(vecs[:,1]) - vals[1]*vecs[:,1]

matrix([[ 0.],
        [ 0.]])

## `loadtxt`

One can also load a 2D grid of values and put them in a 2D array. 

If the file `values.txt` contained the following:

``
1 2 3 4
5 6 7 8
3 4 5 6
``

then

In [66]:
f = open('values.txt', 'w')
f.write("""
1 2 3 4
5 6 7 8
3 4 5 6
""")
f.close()

In [82]:
!more values.txt


1 2 3 4
5 6 7 8
3 4 5 6


In [67]:
a = np.loadtxt("values.txt", float)

In [68]:
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 3.,  4.,  5.,  6.]])

In [69]:
a[0,:]

array([ 1.,  2.,  3.,  4.])

In [70]:
a[:,0]

array([ 1.,  5.,  3.])